[package]
name = "check-suite"
version = "0.1.0"
authors = ["Anthony J. Martinez <anthony@ajmartinez.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
